name: Snowflake Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      - name: Create Snowflake Config
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.github]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
          EOF
          
          chmod 600 ~/.snowflake/config.toml

      - name: Build Project
        run: |
          snow snowpark build --connection github

      - name: Deploy Project
        run: |
          snow snowpark deploy --connection github --replace